// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519182245_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowAnonymousAccess")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_anonymous_access");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EnrollmentOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("enrollment_open");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("CreatorId", "Title")
                        .HasDatabaseName("ix_courses_creator_id_title");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Courses.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_enrollments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_enrollments_user_id");

                    b.HasIndex("CourseId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollments_course_id_user_id");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Courses.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_modules");

                    b.HasIndex("CourseId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_modules_course_id_order_index");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Courses.ModuleResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessPasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("access_password_hash");

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_from");

                    b.Property<DateTime?>("AvailableUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_until");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_module_resources");

                    b.HasIndex("ModuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_module_resources_module_id");

                    b.ToTable("module_resources", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Courses.ResourceComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_markdown");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_resource_comments");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_resource_comments_parent_comment_id");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_resource_comments_resource_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_resource_comments_user_id");

                    b.ToTable("resource_comments", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Courses.ResourceProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_resource_progress");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_resource_progress_resource_id");

                    b.HasIndex("UserId", "ResourceId", "IsCompleted")
                        .HasDatabaseName("ix_resource_progress_user_id_resource_id_is_completed");

                    b.ToTable("resource_progress", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Courses.TAPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanEditContent")
                        .HasColumnType("boolean")
                        .HasColumnName("can_edit_content");

                    b.Property<bool>("CanGrade")
                        .HasColumnType("boolean")
                        .HasColumnName("can_grade");

                    b.Property<bool>("CanManageEnrollments")
                        .HasColumnType("boolean")
                        .HasColumnName("can_manage_enrollments");

                    b.Property<bool>("CanModerateDiscussions")
                        .HasColumnType("boolean")
                        .HasColumnName("can_moderate_discussions");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ta_permissions");

                    b.HasIndex("EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_ta_permissions_enrollment_id");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_ta_permissions_granted_by_user_id");

                    b.ToTable("ta_permissions", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Resources.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InstructionsMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("instructions_markdown");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<decimal?>("PassingScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("passing_score");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<bool>("ShowResults")
                        .HasColumnType("boolean")
                        .HasColumnName("show_results");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_questions");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assessments");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_assessments_resource_id");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Resources.AssessmentQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<decimal>("Points")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("points");

                    b.Property<string>("QuestionDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("question_data");

                    b.Property<string>("QuestionTextMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text_markdown");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("question_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assessment_questions");

                    b.HasIndex("QuestionDataJson")
                        .HasDatabaseName("ix_assessment_questions_question_data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("QuestionDataJson"), "GIN");

                    b.HasIndex("AssessmentId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_assessment_questions_assessment_id_order_index");

                    b.ToTable("assessment_questions", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Resources.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedFileTypes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("allowed_file_types");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GradingSchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("grading_schema");

                    b.Property<string>("InstructionsMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions_markdown");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxFileSizeMb")
                        .HasColumnType("integer")
                        .HasColumnName("max_file_size_mb");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("max_score");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("SubmissionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("submission_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_resource_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Resources.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_markdown");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_resource_id");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Resources.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConstraintsMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("constraints_markdown");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FunctionSignature")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("function_signature");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPractice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_practice");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<int>("MemoryLimitMb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit_mb");

                    b.Property<string>("ProblemStatementMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem_statement_markdown");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_ms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_resource_id");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Resources.ProblemTestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_output");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_data");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSample")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sample");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_problem_test_cases");

                    b.HasIndex("ProblemId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_test_cases_problem_id_order_index");

                    b.ToTable("problem_test_cases", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssessmentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("total_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_assessment_attempts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_assessment_attempts_user_id");

                    b.HasIndex("AssessmentId", "UserId")
                        .HasDatabaseName("ix_assessment_attempts_assessment_id_user_id");

                    b.ToTable("assessment_attempts", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssessmentResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("text")
                        .HasColumnName("feedback_text");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("graded_at");

                    b.Property<Guid?>("GradedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("graded_by_user_id");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("ResponseDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_data");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assessment_responses");

                    b.HasIndex("GradedByUserId")
                        .HasDatabaseName("ix_assessment_responses_graded_by_user_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_assessment_responses_question_id");

                    b.HasIndex("ResponseDataJson")
                        .HasDatabaseName("ix_assessment_responses_response_data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ResponseDataJson"), "GIN");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_assessment_responses_attempt_id_question_id");

                    b.ToTable("assessment_responses", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssignmentGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CanResubmit")
                        .HasColumnType("boolean")
                        .HasColumnName("can_resubmit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("text")
                        .HasColumnName("feedback_text");

                    b.Property<Guid>("GraderId")
                        .HasColumnType("uuid")
                        .HasColumnName("grader_id");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment_grades");

                    b.HasIndex("GraderId")
                        .HasDatabaseName("ix_assignment_grades_grader_id");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_grades_submission_id");

                    b.ToTable("assignment_grades", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssignmentSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("SubmissionText")
                        .HasColumnType("text")
                        .HasColumnName("submission_text");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_on");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_submissions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_assignment_submissions_user_id");

                    b.HasIndex("AssignmentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_submissions_assignment_id_user_id");

                    b.ToTable("assignment_submissions", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Submissions.CodeExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeSnippet")
                        .HasColumnType("text")
                        .HasColumnName("code_snippet");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExecutedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("execution_time_ms");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<int?>("MemoryUsedKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_used_kb");

                    b.Property<Guid?>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_code_execution_logs");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_code_execution_logs_problem_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_code_execution_logs_user_id");

                    b.ToTable("code_execution_logs", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Submissions.ProblemSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("execution_time_ms");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<int?>("MemoryUsedKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_used_kb");

                    b.Property<int?>("PassedTestCases")
                        .HasColumnType("integer")
                        .HasColumnName("passed_test_cases");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submitted_code");

                    b.Property<int?>("TotalTestCases")
                        .HasColumnType("integer")
                        .HasColumnName("total_test_cases");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_problem_submissions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_problem_submissions_user_id");

                    b.HasIndex("ProblemId", "UserId")
                        .HasDatabaseName("ix_problem_submissions_problem_id_user_id");

                    b.ToTable("problem_submissions", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Submissions.ProblemTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualOutput")
                        .HasColumnType("text")
                        .HasColumnName("actual_output");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("execution_time_ms");

                    b.Property<int?>("MemoryUsedKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_used_kb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_problem_test_results");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_problem_test_results_submission_id");

                    b.HasIndex("TestCaseId")
                        .HasDatabaseName("ix_problem_test_results_test_case_id");

                    b.ToTable("problem_test_results", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Courses.Course", b =>
                {
                    b.HasOne("Backend.Models.Users.User", "Creator")
                        .WithMany("Courses")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_users_creator_id");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Backend.Models.Courses.Enrollment", b =>
                {
                    b.HasOne("Backend.Models.Courses.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_courses_course_id");

                    b.HasOne("Backend.Models.Users.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_users_user_id");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Courses.Module", b =>
                {
                    b.HasOne("Backend.Models.Courses.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_modules_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Models.Courses.ModuleResource", b =>
                {
                    b.HasOne("Backend.Models.Courses.Module", "Module")
                        .WithMany("Resources")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_module_resources_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Backend.Models.Courses.ResourceComment", b =>
                {
                    b.HasOne("Backend.Models.Courses.ResourceComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_resource_comments_resource_comments_parent_comment_id");

                    b.HasOne("Backend.Models.Courses.ModuleResource", "Resource")
                        .WithMany("Comments")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_resource_comments_module_resources_resource_id");

                    b.HasOne("Backend.Models.Users.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resource_comments_users_user_id");

                    b.Navigation("ParentComment");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Courses.ResourceProgress", b =>
                {
                    b.HasOne("Backend.Models.Courses.ModuleResource", "Resource")
                        .WithMany("Progress")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_resource_progress_module_resources_resource_id");

                    b.HasOne("Backend.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resource_progress_users_user_id");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Courses.TAPermissions", b =>
                {
                    b.HasOne("Backend.Models.Courses.Enrollment", "Enrollment")
                        .WithOne("TAPermissions")
                        .HasForeignKey("Backend.Models.Courses.TAPermissions", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_ta_permissions_enrollments_enrollment_id");

                    b.HasOne("Backend.Models.Users.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ta_permissions_users_granted_by_user_id");

                    b.Navigation("Enrollment");

                    b.Navigation("GrantedByUser");
                });

            modelBuilder.Entity("Backend.Models.Resources.Assessment", b =>
                {
                    b.HasOne("Backend.Models.Courses.ModuleResource", "Resource")
                        .WithOne("Assessment")
                        .HasForeignKey("Backend.Models.Resources.Assessment", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assessments_module_resources_resource_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Backend.Models.Resources.AssessmentQuestion", b =>
                {
                    b.HasOne("Backend.Models.Resources.Assessment", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_questions_assessments_assessment_id");

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("Backend.Models.Resources.Assignment", b =>
                {
                    b.HasOne("Backend.Models.Courses.ModuleResource", "Resource")
                        .WithOne("Assignment")
                        .HasForeignKey("Backend.Models.Resources.Assignment", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assignments_module_resources_resource_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Backend.Models.Resources.Lesson", b =>
                {
                    b.HasOne("Backend.Models.Courses.ModuleResource", "Resource")
                        .WithOne("Lesson")
                        .HasForeignKey("Backend.Models.Resources.Lesson", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lessons_module_resources_resource_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Backend.Models.Resources.Problem", b =>
                {
                    b.HasOne("Backend.Models.Courses.ModuleResource", "Resource")
                        .WithOne("Problem")
                        .HasForeignKey("Backend.Models.Resources.Problem", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_problems_module_resources_resource_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Backend.Models.Resources.ProblemTestCase", b =>
                {
                    b.HasOne("Backend.Models.Resources.Problem", "Problem")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_problem_test_cases_problems_problem_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssessmentAttempt", b =>
                {
                    b.HasOne("Backend.Models.Resources.Assessment", "Assessment")
                        .WithMany("Attempts")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assessment_attempts_assessments_assessment_id");

                    b.HasOne("Backend.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_assessment_attempts_users_user_id");

                    b.Navigation("Assessment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssessmentResponse", b =>
                {
                    b.HasOne("Backend.Models.Submissions.AssessmentAttempt", "Attempt")
                        .WithMany("Responses")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assessment_responses_assessment_attempts_attempt_id");

                    b.HasOne("Backend.Models.Users.User", "GradedByUser")
                        .WithMany()
                        .HasForeignKey("GradedByUserId")
                        .HasConstraintName("fk_assessment_responses_users_graded_by_user_id");

                    b.HasOne("Backend.Models.Resources.AssessmentQuestion", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_responses_assessment_questions_question_id");

                    b.Navigation("Attempt");

                    b.Navigation("GradedByUser");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssignmentGrade", b =>
                {
                    b.HasOne("Backend.Models.Users.User", "Grader")
                        .WithMany()
                        .HasForeignKey("GraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_grades_users_grader_id");

                    b.HasOne("Backend.Models.Submissions.AssignmentSubmission", "Submission")
                        .WithOne("Grade")
                        .HasForeignKey("Backend.Models.Submissions.AssignmentGrade", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assignment_grades_assignment_submissions_submission_id");

                    b.Navigation("Grader");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssignmentSubmission", b =>
                {
                    b.HasOne("Backend.Models.Resources.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_submissions_assignments_assignment_id");

                    b.HasOne("Backend.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_submissions_users_user_id");

                    b.Navigation("Assignment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Submissions.CodeExecutionLog", b =>
                {
                    b.HasOne("Backend.Models.Resources.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_code_execution_logs_problems_problem_id");

                    b.HasOne("Backend.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_code_execution_logs_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Submissions.ProblemSubmission", b =>
                {
                    b.HasOne("Backend.Models.Resources.Problem", "Problem")
                        .WithMany("Submissions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_problem_submissions_problems_problem_id");

                    b.HasOne("Backend.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_problem_submissions_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Submissions.ProblemTestResult", b =>
                {
                    b.HasOne("Backend.Models.Submissions.ProblemSubmission", "Submission")
                        .WithMany("TestResults")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_test_results_problem_submissions_submission_id");

                    b.HasOne("Backend.Models.Resources.ProblemTestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_problem_test_results_test_cases_test_case_id");

                    b.Navigation("Submission");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("Backend.Models.Courses.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Backend.Models.Courses.Enrollment", b =>
                {
                    b.Navigation("TAPermissions");
                });

            modelBuilder.Entity("Backend.Models.Courses.Module", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Backend.Models.Courses.ModuleResource", b =>
                {
                    b.Navigation("Assessment");

                    b.Navigation("Assignment");

                    b.Navigation("Comments");

                    b.Navigation("Lesson");

                    b.Navigation("Problem");

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("Backend.Models.Courses.ResourceComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Backend.Models.Resources.Assessment", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Backend.Models.Resources.AssessmentQuestion", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Backend.Models.Resources.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Backend.Models.Resources.Problem", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssessmentAttempt", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Backend.Models.Submissions.AssignmentSubmission", b =>
                {
                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Backend.Models.Submissions.ProblemSubmission", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("Backend.Models.Users.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Courses");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
