// <auto-generated />
using System;
using Backend.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801185910_AddedFile")]
    partial class AddedFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Api.Core.Entities.Assessments.AssessmentAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssessmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assessment_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("total_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_assessment_attempts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_assessment_attempts_user_id");

                    b.HasIndex("AssessmentId", "UserId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_assessment_attempts_assessment_id_user_id_attempt_number");

                    b.ToTable("assessment_attempts", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Assessments.AttemptAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("text")
                        .HasColumnName("feedback_text");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("graded_at");

                    b.Property<long?>("GradedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("graded_by_user_id");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<string>("ResponseDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_data");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assessment_responses");

                    b.HasIndex("GradedByUserId")
                        .HasDatabaseName("ix_assessment_responses_graded_by_user_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_assessment_responses_question_id");

                    b.HasIndex("ResponseDataJson")
                        .HasDatabaseName("ix_assessment_responses_response_data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ResponseDataJson"), "GIN");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_assessment_responses_attempt_id_question_id");

                    b.ToTable("assessment_responses", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Assignments.AssignmentGrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedbackText")
                        .HasColumnType("text")
                        .HasColumnName("feedback_text");

                    b.Property<long>("GraderId")
                        .HasColumnType("bigint")
                        .HasColumnName("grader_id");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment_grades");

                    b.HasIndex("GraderId")
                        .HasDatabaseName("ix_assignment_grades_grader_id");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_grades_submission_id");

                    b.ToTable("assignment_grades", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Assignments.AssignmentSubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("SubmissionText")
                        .HasColumnType("text")
                        .HasColumnName("submission_text");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_on");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_submissions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_assignment_submissions_user_id");

                    b.HasIndex("AssignmentId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_submissions_assignment_id_user_id")
                        .HasFilter("is_deleted = false");

                    b.ToTable("assignment_submissions", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.Assessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GradingSchemaJson")
                        .HasColumnType("text")
                        .HasColumnName("grading_schema_json");

                    b.Property<string>("InstructionsMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("instructions_markdown");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<bool>("ShowResults")
                        .HasColumnType("boolean")
                        .HasColumnName("show_results");

                    b.Property<bool>("ShuffleQuestions")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_questions");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assessments");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_assessments_resource_id");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.AssessmentQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssessmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assessment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<decimal>("Points")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("points");

                    b.Property<string>("QuestionDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("question_data");

                    b.Property<string>("QuestionTextMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text_markdown");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("question_type");

                    b.Property<long>("SectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assessment_questions");

                    b.HasIndex("QuestionDataJson")
                        .HasDatabaseName("ix_assessment_questions_question_data");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("QuestionDataJson"), "GIN");

                    b.HasIndex("AssessmentId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_assessment_questions_assessment_id_order_index")
                        .HasFilter("is_deleted = false");

                    b.ToTable("assessment_questions", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedFileTypes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("allowed_file_types");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GradingSchemaJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("grading_schema");

                    b.Property<string>("InstructionsMD")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions_md");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("MaxAttempt")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempt");

                    b.Property<int>("MaxFileSizeKb")
                        .HasColumnType("integer")
                        .HasColumnName("max_file_size_kb");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<string>("SubmissionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("submission_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignments_resource_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.CodingProblem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConstraintsMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("constraints_markdown");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("FunctionSignature")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("function_signature");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPractice")
                        .HasColumnType("boolean")
                        .HasColumnName("is_practice");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<int>("MemoryLimitKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_limit_kb");

                    b.Property<string>("ProblemStatementMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem_statement_markdown");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<int>("TimeLimitMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_ms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_resource_id");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.FileAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Sha256Hash")
                        .HasColumnType("text")
                        .HasColumnName("sha256hash");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UploaderId")
                        .HasColumnType("bigint")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_file_assets");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("ix_file_assets_uploader_id");

                    b.ToTable("file_assets", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_markdown");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_resource_id");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.ProblemTestCase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_output");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_data");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSample")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sample");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<long>("ProblemId")
                        .HasColumnType("bigint")
                        .HasColumnName("problem_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_problem_test_cases");

                    b.HasIndex("ProblemId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_test_cases_problem_id_order_index")
                        .HasFilter("is_deleted = false");

                    b.ToTable("problem_test_cases", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_markdown");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_comment_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_resource_comments");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_resource_comments_activity_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_resource_comments_parent_comment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_resource_comments_user_id");

                    b.ToTable("resource_comments", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BackgroundFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("background_file_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EnrollmentOpen")
                        .HasColumnType("boolean")
                        .HasColumnName("enrollment_open");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex("BackgroundFileId")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_background_file_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_courses_department_id");

                    b.HasIndex("CreatorId", "Title")
                        .HasDatabaseName("ix_courses_creator_id_title");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.CourseModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_modules");

                    b.HasIndex("CourseId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_modules_course_id_order_index")
                        .HasFilter("is_deleted = false");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.CourseResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("access_password");

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_from");

                    b.Property<DateTime?>("AvailableUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_until");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("module_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_course_resources");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_course_resources_module_id");

                    b.ToTable("course_resources", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Enrollment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_enrollments");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_enrollments_user_id");

                    b.HasIndex("CourseId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollments_course_id_user_id")
                        .HasFilter("is_deleted = false");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.TAPermissions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanGrade")
                        .HasColumnType("boolean")
                        .HasColumnName("can_grade");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("GrantedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ta_permissions");

                    b.HasIndex("EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_ta_permissions_enrollment_id");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_ta_permissions_granted_by_user_id");

                    b.ToTable("ta_permissions", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Judge.CodeExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeSnippet")
                        .HasColumnType("text")
                        .HasColumnName("code_snippet");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExecutedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("execution_time_ms");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<int?>("MemoryUsedKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_used_kb");

                    b.Property<long?>("ProblemId")
                        .HasColumnType("bigint")
                        .HasColumnName("problem_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_code_execution_logs");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_code_execution_logs_problem_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_code_execution_logs_user_id");

                    b.ToTable("code_execution_logs", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Judge.ProblemSubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("execution_time_ms");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<int?>("MemoryUsedKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_used_kb");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int?>("PassedTestCases")
                        .HasColumnType("integer")
                        .HasColumnName("passed_test_cases");

                    b.Property<long>("ProblemId")
                        .HasColumnType("bigint")
                        .HasColumnName("problem_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submitted_code");

                    b.Property<int?>("TotalTestCases")
                        .HasColumnType("integer")
                        .HasColumnName("total_test_cases");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_problem_submissions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_problem_submissions_user_id");

                    b.HasIndex("ProblemId", "UserId")
                        .HasDatabaseName("ix_problem_submissions_problem_id_user_id");

                    b.ToTable("problem_submissions", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Judge.ProblemTestResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualOutput")
                        .HasColumnType("text")
                        .HasColumnName("actual_output");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("ExecutionTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("execution_time_ms");

                    b.Property<int?>("MemoryUsedKb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_used_kb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("submission_id");

                    b.Property<long>("TestCaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_case_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_problem_test_results");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("ix_problem_test_results_submission_id");

                    b.HasIndex("TestCaseId")
                        .HasDatabaseName("ix_problem_test_results_test_case_id");

                    b.ToTable("problem_test_results", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Learning.ResourceProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_resource_progress");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("ix_resource_progress_resource_id");

                    b.HasIndex("UserId", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_resource_progress_user_id_resource_id");

                    b.ToTable("resource_progress", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Assessments.AssessmentAttempt", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Content.Assessment", "Assessment")
                        .WithMany("Attempts")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assessment_attempts_assessments_assessment_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_assessment_attempts_users_user_id");

                    b.Navigation("Assessment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Assessments.AttemptAnswer", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Assessments.AssessmentAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assessment_responses_assessment_attempts_attempt_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "GradedByUser")
                        .WithMany()
                        .HasForeignKey("GradedByUserId")
                        .HasConstraintName("fk_assessment_responses_users_graded_by_user_id");

                    b.HasOne("Backend.Api.Core.Entities.Content.AssessmentQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_responses_assessment_questions_question_id");

                    b.Navigation("Attempt");

                    b.Navigation("GradedByUser");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Assignments.AssignmentGrade", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Users.User", "Grader")
                        .WithMany()
                        .HasForeignKey("GraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_grades_users_grader_id");

                    b.HasOne("Backend.Api.Core.Entities.Assignments.AssignmentSubmission", "Submission")
                        .WithOne("Grade")
                        .HasForeignKey("Backend.Api.Core.Entities.Assignments.AssignmentGrade", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assignment_grades_assignment_submissions_submission_id");

                    b.Navigation("Grader");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Assignments.AssignmentSubmission", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Content.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_submissions_assignments_assignment_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_submissions_users_user_id");

                    b.Navigation("Assignment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.Assessment", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.CourseResource", "Resource")
                        .WithOne("Assessment")
                        .HasForeignKey("Backend.Api.Core.Entities.Content.Assessment", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assessments_course_resources_resource_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.AssessmentQuestion", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Content.Assessment", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_questions_assessments_assessment_id");

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.Assignment", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.CourseResource", "Resource")
                        .WithOne("Assignment")
                        .HasForeignKey("Backend.Api.Core.Entities.Content.Assignment", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assignments_course_resources_resource_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.CodingProblem", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.CourseResource", "Resource")
                        .WithOne("Problem")
                        .HasForeignKey("Backend.Api.Core.Entities.Content.CodingProblem", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_problems_course_resources_resource_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.FileAsset", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Users.User", "User")
                        .WithMany("FileAssets")
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_assets_users_uploader_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.Lesson", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.CourseResource", "Resource")
                        .WithOne("Lesson")
                        .HasForeignKey("Backend.Api.Core.Entities.Content.Lesson", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_lessons_course_resources_resource_id");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.ProblemTestCase", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Content.CodingProblem", "Problem")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_problem_test_cases_coding_problems_problem_id");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Comment", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.CourseResource", "Resource")
                        .WithMany("Comments")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_resource_comments_course_resources_activity_id");

                    b.HasOne("Backend.Api.Core.Entities.Courses.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_resource_comments_resource_comments_parent_comment_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resource_comments_users_user_id");

                    b.Navigation("ParentComment");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Course", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Content.FileAsset", "BackgroundFile")
                        .WithOne("Course")
                        .HasForeignKey("Backend.Api.Core.Entities.Courses.Course", "BackgroundFileId")
                        .HasConstraintName("fk_courses_file_assets_background_file_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "Creator")
                        .WithMany("Courses")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_courses_users_creator_id");

                    b.HasOne("Backend.Api.Core.Entities.Courses.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("fk_courses_departments_department_id");

                    b.Navigation("BackgroundFile");

                    b.Navigation("Creator");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.CourseModule", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_modules_courses_course_id");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.CourseResource", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.CourseModule", "Module")
                        .WithMany("Resources")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_course_resources_course_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Enrollment", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_courses_course_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_users_user_id");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.TAPermissions", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.Enrollment", "Enrollment")
                        .WithOne("TAPermissions")
                        .HasForeignKey("Backend.Api.Core.Entities.Courses.TAPermissions", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_ta_permissions_enrollments_enrollment_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ta_permissions_users_granted_by_user_id");

                    b.Navigation("Enrollment");

                    b.Navigation("GrantedByUser");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Judge.CodeExecutionLog", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Content.CodingProblem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_code_execution_logs_coding_problems_problem_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_code_execution_logs_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Judge.ProblemSubmission", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Content.CodingProblem", "Problem")
                        .WithMany("Submissions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_problem_submissions_coding_problems_problem_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_problem_submissions_users_user_id");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Judge.ProblemTestResult", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Judge.ProblemSubmission", "Submission")
                        .WithMany("TestResults")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_test_results_problem_submissions_submission_id");

                    b.HasOne("Backend.Api.Core.Entities.Content.ProblemTestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_problem_test_results_problem_test_cases_test_case_id");

                    b.Navigation("Submission");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Learning.ResourceProgress", b =>
                {
                    b.HasOne("Backend.Api.Core.Entities.Courses.CourseResource", "Resource")
                        .WithMany("Progress")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_resource_progress_course_resources_resource_id");

                    b.HasOne("Backend.Api.Core.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resource_progress_users_user_id");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Assessments.AssessmentAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Assignments.AssignmentSubmission", b =>
                {
                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.Assessment", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.AssessmentQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.CodingProblem", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Content.FileAsset", b =>
                {
                    b.Navigation("Course")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.CourseModule", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.CourseResource", b =>
                {
                    b.Navigation("Assessment");

                    b.Navigation("Assignment");

                    b.Navigation("Comments");

                    b.Navigation("Lesson");

                    b.Navigation("Problem");

                    b.Navigation("Progress");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Courses.Enrollment", b =>
                {
                    b.Navigation("TAPermissions");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Judge.ProblemSubmission", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("Backend.Api.Core.Entities.Users.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("FileAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
